name: Rust


on:
  push:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

env:
  CARGO_TERM_COLOR: always
  LIBCLANG_PATH: /usr/lib/llvm-10/lib/

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Install apt-get
      run: sudo apt-get install -y clang llvm libicu66
    - name: List libs
      run: ls -l /usr/lib
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          components: rustfmt, clippy
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests 
      run: cargo test --verbose
    - name: Run tests (with address sanitizer)
      run: LSAN_OPTIONS=suppressions=san.supp RUSTFLAGS="-Zsanitizer=address" cargo +nightly test --verbose
